import System
import System.IO
import System.Environment

import Test.Falderal.Common
import Test.Falderal.Loader (loadFile)
import Test.Falderal.Runner
import Test.Falderal.Formatter (format)
import Test.Falderal.Reporter (report)

--
-- This module contains entry points to Falderal functionality intended
-- for use by users.
--

main :: IO ()
main = do
    args <- getArgs
    dispatch args

dispatch ("format":formatName:fileName:[]) = do
    (lines, blocks) <- loadFile fileName
    text <- return $ format formatName lines blocks
    putStr outputText

--
-- Requires ghc.  Requires Test.Falderal is in the package path
-- (easiest way to ensure this is to install it as a Cabal package)
-- TODO: require only runhaskell.
-- TODO: allow "runhaskell" to be overridden with a cmd line opt.
-- TODO: determine which formats need to be generated by
--       looking at the loaded tests
--

dispatch ("test":reportFormat:fileName:[]) = do
    (lines, blocks) <- loadFile fileName
    haskellBlocks <- return $ getHaskellBlocks blocks
    shellBlocks <- return $ getShellBlocks blocks
    testHaskell haskellBlocks reportFormat fileName
    testShell shellBlocks reportFormat fileName
    -- exitWith exitCode

testHaskell [] _ _ = do
    return 0
testHaskell blocks reportFormat fileName = do
    outputFileHandle <- openFile "GeneratedFalderalTests.hs" WriteMode
    text <- return $ format "haskell" lines haskellBlocks
    hPutStr outputFileHandle text
    hClose outputFileHandle
    exitCode <- system "ghc GeneratedFalderalTests.hs -e testModule"
    system "rm -f GeneratedFalderalTests.hs"
    return exitCode

testShell [] _ _ = do
    return 0
testShell blocks reportFormat fileName = do
    outputFileHandle <- openFile "GeneratedFalderalTests.sh" WriteMode
    text <- return $ format "shell" lines haskellBlocks
    hPutStr outputFileHandle text
    hClose outputFileHandle
    exitCode <- system "bash GeneratedFalderalTests.sh"
    system "rm -f GeneratedFalderalTests.sh"
    return exitCode

getHaskellBlocks (test@(Test (HaskellTest _ _) _ _ _):rest) =
    (test:(getHaskellBlocks rest))
getHaskellBlocks (_:rest) =
    getHaskellBlocks rest
getHaskellBlocks [] =
    []

getShellBlocks (test@(Test (ShellTest _ _) _ _ _):rest) =
    (test:(getShellBlocks rest))
getShellBlocks (_:rest) =
    getShellBlocks rest
getShellBlocks [] =
    []

data Block = Section String
           | Test TestType String String Expectation
           deriving (Show, Eq, Ord)

dispatch _ = do
    putStrLn "Usage: falderal command {args}"
    putStrLn "where command is one of:"
    putStrLn "    format format-name input-falderal-filename"
    putStrLn "    test report-style input-falderal-filename"
